### ISSUE TITLE
Where is the aerial_robotics/src/ folder?

### ISSUE THREAD

**Issue by yxt916** [Shubham-Sahoo/Obstacle-Avoidance-on-UAV#1]
IN "Now copy the folders from aerial_robotics/src/ folder into ~/catkin_ws/src/ and compile it"
Where is the "aerial_robotics/src/ folder?"
I can't find it./(ㄒoㄒ)/~~

**Comment by Shubham-Sahoo** [comment]
> IN "Now copy the folders from aerial_robotics/src/ folder into ~/catkin_ws/src/ and compile it"
> Where is the "aerial_robotics/src/ folder?"
> I can't find it./(ㄒoㄒ)/~~

Thanks for pointing out the issue. Actually the readme is not updated. You can copy the drone_ws/src folder in your catkin/src. Sorry for the inconvenience. I will update the readme soon.
